apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pheeimporterrdbmses.my.custom.group # Use the current naming convention
spec:
  group: my.custom.group
  names:
    kind: PhEeImporterRdbms
    listKind: PhEeImporterRdbmsList
    plural: pheeimporterrdbmses
    singular: pheeimporterrdbms
    shortNames:  # Add short names if required
      - peeirdbms
  scope: Namespaced
  versions:
    - name: v1 
      served: true
      storage: true
      subresources:
        status: {}  # Ensure status is defined as a subresource
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enabled:
                  type: boolean
                  default: true
                volMount:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false
                    name:
                      type: string 
                replicas:
                  type: integer
                image:
                  type: string
                containerPort:
                  type: integer                  
                springProfilesActive:
                  type: string
                environment:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                      valueFrom:
                        type: object
                        properties:
                          secretKeyRef:
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string                          
                datasource:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                    host:
                      type: string
                    port:
                      type: integer
                    schema:
                      type: string
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                logging:
                  type: object
                  properties:
                    levelRoot:
                      type: string
                    patternConsole:
                      type: string
                javaToolOptions:
                  type: string
                bucketName:
                  type: string
                livenessProbe:
                  type: object
                  properties:
                    path:
                      type: string
                    port:
                      type: integer
                    initialDelaySeconds:
                      type: integer
                    periodSeconds:
                      type: integer
                    failureThreshold:
                      type: integer
                    timeoutSeconds:
                      type: integer
                readinessProbe:
                  type: object
                  properties:
                    path:
                      type: string
                    port:
                      type: integer
                    initialDelaySeconds:
                      type: integer
                    periodSeconds:
                      type: integer
                    failureThreshold:
                      type: integer
                    timeoutSeconds:
                      type: integer
                ingress:        # New Ingress Configuration Section 
                  type: object
                  properties:  
                    className:
                      type: string
                    annotations:
                      type: object
                      additionalProperties:
                        type: string
                    tls:
                      type: array
                      items:
                        type: object
                        properties:
                          hosts:
                            type: array
                            items:
                              type: string
                          secretName:
                            type: string
                    rules:
                      type: array
                      items:
                        type: object
                        properties:
                          host:
                            type: string
                          paths:
                            type: array
                            items:
                              type: object
                              properties:
                                path:
                                  type: string
                                pathType:
                                  type: string
                                backend:
                                  type: object
                                  properties:
                                    service:
                                      type: object
                                      properties:
                                        name:
                                          type: string
                                        port:
                                          type: object
                                          properties:
                                            number:
                                              type: integer
                services:  # New Services Configuration Section
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      ports:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            port:
                              type: integer
                            targetPort:
                              type: integer
                            protocol:
                              type: string
                              enum:
                                - TCP
                                - UDP
                      selector:
                        type: object
                        additionalProperties:
                          type: string
                      type:
                        type: string
                        enum:
                          - ClusterIP
                          - NodePort
                          - LoadBalancer
                      annotations:
                        type: object
                        additionalProperties:
                          type: string
                      sessionAffinity:
                        type: string
                        enum:
                          - None
                          - ClientIP                                        
                rbacEnabled:  # Toggle for RBACs
                  type: boolean
                  default: false
                secretEnabled:  # Toggle for Secrets
                  type: boolean
                  default: false
                configMapEnabled:  # Toggle for ConfigMaps
                  type: boolean
                  default: false
                ingressEnabled:  # Toggle for Ingress
                  type: boolean
                  default: false
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
                errorMessage:
                  type: string
                lastAppliedImage:
                  type: string
                ready:
                  type: boolean
