apiVersion: my.custom.group/v1
kind: PhEeImporterRdbms
metadata:
  name: ph-ee-importer-rdbms
  namespace: paymenthub
spec:
  enabled: true
  replicas: 1
  image: docker.io/openmf/ph-ee-importer-rdbms:v1.13.1  # Updated image version
  springProfilesActive: local,tenantsConnection
  datasource:
    username: mifos
    password: password
    host: operationsmysql
    port: 3306
    schema: tenants
  logging:
    levelRoot: INFO
    patternConsole: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  javaToolOptions: "-Xmx256M"
  bucketName: paymenthub-ee  # Corrected bucket name
  # livenessProbe:
  #   path: /actuator/health/liveness
  #   port: 9191
  #   initialDelaySeconds: 120
  #   periodSeconds: 30
  #   failureThreshold: 3
  #   timeoutSeconds: 5
  # readinessProbe:
  #   path: /actuator/health/readiness
  #   port: 9191
  #   initialDelaySeconds: 120
  #   periodSeconds: 30
  #   failureThreshold: 3
  #   timeoutSeconds: 5
  rbacEnabled: true  # Toggle for RBACs (optional, ensure it's necessary)
  secretEnabled: true  # Toggle for Secrets (relevant due to the usage of secrets in the deployment)
  configMapEnabled: true  # Enabled to match the usage of the ConfigMap `ph-ee-config`
  ingressEnabled: false  # Ingress not mentioned, keep as false unless required
